### ISSUE TITLE
[Smoke Test] Onboarding guidance blinks search bar

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#788] opened 2017-09-15 01:37 UTC
See [screen record](https://drive.google.com/file/d/0B0uVZlaHN366eUZmMGYwSWgwY2M/view?usp=sharing)

Build: 1050
DuT: Oppo, Advan

**Comment by chianger** [comment] 2017-09-15 06:53
It's the fading effect by design so won't fix.

**Closed by chianger** 2017-09-15 06:53 UTC
Labels: Bug, Comp/General
