### ISSUE TITLE
Deleting a custom top site makes its record in History gone

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#815] opened 2017-09-18 08:11 UTC
**STR**
1. Remove one or more default top sites
2. Visit a site for several times (yahoo.com for example) -> it becomes top site _X_
3. Delete _X_ -> it will also disappear in History

**Build:** 1072

**Comment by mTwTm** [comment] 2017-09-18 08:39
Sort of duplicate of #349

**Comment by chianger** [comment] 2017-09-20 08:13
need PM decision

**Comment by Ben-YPLai** [comment] 2017-09-29 01:12
It will not disappear now.
related to 874

**Comment by chianger** [comment] 2017-10-02 07:50
not happening anymore on build 0.8.1413

**Closed by chianger** 2017-10-02 07:50 UTC
Labels: Comp/History, P1.5, P2/P3
