### ISSUE TITLE
Missing favicons for some websites

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#427] opened 2017-08-28 06:41 UTC
Not sure if it's a follow up for #309, still file it for tracing.

STR:
- Visit tons of websites and observe browsing history.

![no_favicon](https://user-images.githubusercontent.com/1625148/29762030-cdde2f7e-8bfe-11e7-83f6-5dea7f6457d4.png)

**Comment by Conjuror** [comment] 2017-08-28 06:46
More information about the issue: this may due to the website loading is incomplete. I was attempting to load a lot of websites in series and didn't wait for everypage to be loaded.

if it's about redirect, this issue is related to #360. Otherwise, about unfinished loading, we should bypass the page which is not finished loading by design.

**Comment by Conjuror** [comment] 2017-08-28 06:56
It seems that we don't need to brute-force test to get into the situation. It happens on my normal browsing experience as well.

**Comment by chianger** [comment] 2017-08-30 03:48
QAWanted for clear STR so that we can check.

**Comment by mTwTm** [comment] 2017-09-19 15:28
We've reduce most of the cases that we can handle such as #705 #490 which saves history entries without getting the favicon. The rest should be cases that we can't handle: such as 1) This site is a redirect link and doesn't have a favicon and 2) The user exits early so the favicon is not loaded for this entry.

For these reasons, I'm moving this to decision pending.

**Comment by Conjuror** [comment] 2017-09-20 06:45
From QA's viewpoints, if that's the limitation we have for now, suggest to put as P2 and revisit how to enhance favicons display in the future release after 1.0 is shipped.

**Comment by chianger** [comment] 2017-10-02 08:02
QAWanted to verify if this still happens.

**Comment by chianger** [comment] 2017-10-09 09:08
@dakaizou

**Comment by dakaizou** [comment] 2017-10-09 09:44
This is still happening, but there will be placeholder now since we're using initial character

**Comment by chianger** [comment] 2017-10-11 03:48
Latest comment is current expected behavior

**Closed by chianger** 2017-10-11 03:48 UTC
Labels: Bug, Comp/History, QAwanted

**Comment by dakaizou** [comment] 2017-10-11 07:12
verified since it's expected
