### ISSUE TITLE
default search engine to set to Google

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Zerda#888] opened 2017-09-21 03:10 UTC

**Comment by Conjuror** [comment] 2017-09-21 03:11
related to #541

**Comment by chianger** [comment] 2017-09-21 03:59
QAWanted to confirm this. It's supposedly fixed already.

**Comment by dakaizou** [comment] 2017-09-21 05:27
Looks good on Samsung, Advan, Oppo

**Comment by Conjuror** [comment] 2017-09-22 01:56
It seems to be a migration issue if you installed previous version before and didn't remove its data completely. If we cannot reproduce it in the following week, suggest to **CLOSE** it as invalid.

**Comment by Conjuror** [comment] 2017-09-25 06:26
Closed as invalid due to QA cannot reproduce it anymore.

**Closed by Conjuror** 2017-09-25 06:26 UTC
Labels: Bug, QAwanted
