### ISSUE TITLE
FAB should hide during playing video

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Zerda#110] opened 2017-08-02 08:16 UTC
FAB should hide during playing video, such as YouTube

**Comment by mTwTm** [comment] 2017-08-02 08:29
Can't reproduce, possibly affected by #119

**Comment by mTwTm** [comment] 2017-08-02 08:29
^ If this issue is about full screen mode

**Comment by Conjuror** [comment] 2017-08-02 08:42
I think this is for full screen mode. During full screen mode, FAB won't disappear.

**Comment by chianger** [comment] 2017-08-10 02:51
No FAB now let's close it.

**Closed by chianger** 2017-08-10 02:51 UTC
Labels: Bug, UX

**Comment by dakaizou** [comment] 2017-08-16 06:01
Invalid
